### ISSUE TITLE
Bug Urgent: Automatic calculation of IDP figure based on the number households does not work

### ISSUE THREAD

**Issue by IvanaHajz** [idmc-labs/idmc-database-feedback#44]
When creating a report and using the number of households displaced, the automatic calculation does not work. As a consequence, a wrong figure also appears on the event form.

**Comment by allochi** [comment]
Thanks Ivanna, this has been resolved, please confirm.

**Comment by IvanaHajz** [comment]
Thank you Ali for looking into it that quickly. However, it is still not working for me - before you looked into it, the number of households and people was the same, now, the number of people is always 0, does not matter what figure I enter for households. Not sure why.
